### ISSUE TITLE
Bug: load foregin module error

### ISSUE THREAD

**Issue by liting-yes** [vuejs/repl#115]
I want to use **repl** as a third-party dependency, but monaco doesn't meet expectations

https://stackblitz.com/edit/vitejs-vite-b2a1x1?file=src%2FApp.vue

<img width="1412" alt="Screenshot 2023-06-25 at 11 18 15" src="https://github.com/vuejs/repl/assets/69500429/6279de01-8638-475b-9b09-3cb092153d32">

**Comment by fanckush** [comment]
Same, I can't use Monaco Editor and get the same error

**Comment by runlong-yao** [comment]
It's gone in v2.5.0
