### ISSUE TITLE
is not compatible with nuxt 3

### ISSUE THREAD

**Issue by kromate** [vuejs/repl#135]
when I installed the package in a nuxt 3 application it doesn't load properly
<img width="1440" alt="Screenshot 2023-07-13 at 20 54 42" src="https://github.com/vuejs/repl/assets/52849936/b59140ed-50ed-47a0-9dca-77a7dc69e3ba">

**Comment by kromate** [comment]
@yyx990803 @

**Comment by sxzz** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Comment by kromate** [comment]
https://stackblitz.com/edit/nuxt-starter-zbjalk?file=app.vue

@sxzz here is a stackblitz exam

**Comment by sxzz** [comment]
@kromate it's a empty nuxt starter template.

**Comment by kromate** [comment]
Sorry about that

seems like I didn't save 
https://stackblitz.com/edit/nuxt-starter-zbjalk?file=app.vue

This link such work, double checked 
@sxzz

**Comment by sxzz** [comment]
```vue
<Repl :editor="Monaco" style="height: 100vh" />
```

You need to add the height property

**Comment by kromate** [comment]
@sxzz this fixes the height issue, thanks

but I still don't get the volar autocomplete and inference e.g 
`const msg = ref('Hello World!')`
when i try to type
`msg.`
somewhere else in the code it doesn't show value just generics

I believe this is a nuxt, would just convert the project to a vue3 application instead of a nuxt 3 one because that seems to work just fine

thank you very much @sxzz
