### ISSUE TITLE
What url for `vue.esm-browser.js` should I put into the import map?

### ISSUE THREAD

**Issue by silentmantra** [vuejs/repl#143]
I'd like to fix this error (I try to use `compile()`):
```
Runtime compilation is not supported in this build of Vue. Use "vue.esm-browser.js" instead.
 at <Repl>
```

**Comment by sxzz** [comment]
<img width="826" alt="image" src="https://github.com/vuejs/repl/assets/6481596/5b7276e9-b66e-45d3-bc46-2e8bd2f3a818">
Remove `runtime.` in the `Import Map` tab.
