### ISSUE TITLE
Unable to properly showcase the effect of Cesium in the repl

### ISSUE THREAD

**Issue by JensonMiao** [vuejs/repl#188]
I want to load Cesium content in the REPL, but I found that I can't display the full content of Cesium. The correct display should show the appearance of the Earth, but it is not rendered in the REPL
![image](https://github.com/vuejs/repl/assets/46488783/79350dc9-6b9f-4237-83b7-b03a4cd1adfd)
correct display：
![image](https://github.com/vuejs/repl/assets/46488783/c5826fec-b5ab-428d-ac9c-1ce1503edf3b)
I have a small demo source code here:
https://github.com/JensonMiao/repl-cesium-demo

**Comment by sxzz** [comment]
Please use ESM dependency and configure import maps https://github.com/WICG/import-maps
