### ISSUE TITLE
Showoutput argument not working

### ISSUE THREAD

**Issue by DarrenXu94** [vuejs/repl#189]
https://stackblitz.com/edit/vitejs-vite-ndcbpe?file=src%2Fcomponents%2FExampleRepl.vue

I've added the showOutput arg into the ReplStore constructor but it doesn't seem to be doing anything. Is it supposed to hide one of the panels?

Using @vue/repl": "^3.0.0

**Comment by pdanpdan** [comment]
It selects which half (code or output) is displayed by default on small screens.

**Comment by nemo-shen** [comment]
@DarrenXu94 
If your screen width is less than 720 pixels, it will be considered as a mobile device, and at this time, either the editor or the preview will be automatically hidden.
You can see this code: https://github.com/vuejs/repl/blob/main/src/SplitPane.vue#L162
