### ISSUE TITLE
Import the complete dependency package

### ISSUE THREAD

**Issue by xstxhjh** [vuejs/repl#192]
How to import the complete dependency package, I have to import 'ol/layer' one by one, 'ol/source', 'ol/proj'.

[Demo](https://play.vuejs.org/#eNqdVv9P2zgU/1esnE6UuzRpaZFOOZj4ojE4DZjo7qTTuh/c5KU1OHZmO6UF9X/fs52UtIwJ1mki9nvv48/7aj8Gx2UZzSsIkuDAQFFyauDdWBBykLE5YdnhOCgoE92CluOApJxq7bbK7kQuxoFXjVEXvw7iFgIudapYaYgGU5W4w4pSKkMeySUtQ/Ifg3uyIrmSBdmRfOdva7JW+cw4tKQxp0tQVmetcT26bCtoWakUNjSs7KMUH6lpK5ZK3m6oSXEpK2EgC4meUc7l/Q3kIVGQr80wPp5fKoU2BL0nhy3lzi4KvWhuvXoma6RMMDwH5QjeySnXsC3F0KC4s0sO35FHG1sLGM0prwD3BYLbuHWciJAUkLdKWp52vvT7g2h/MNzv9UMyGEbDYb833P+6G3qLBymLhAzdamUPJ9abjQOQQoNvqJqCSchOUwI7NYxLh07IF78kztDmrLG0vznTbMIhIUZVUBvan09V4mwwi20TQirF8byZMaVO4thym4L8FqUiPlbph4tRrECbWIOasxR0fDpjgl4LzgScyqKoMITLGD0YoQKo2CCl+PFhFT8u8f9i1fC3v1UTk9bn1/qvjXrSiv1TvOyHT+M6aNY9lKycdF1NnVYS68y6WnAoB7HvjbpPzJLblvnDa2NjdTV7YGKa4LfKQNleq3OlpkwkpOdWJc0yp2WXKwtVcWTKmcfhTJuuw8ZYS+E4WqUo5UBVzhZezZdE/5k0oTkWV1OFmErGMbgJmbEsA+EIZExju+PehMv0zm3lUuCh7AHP9CSxtg2WKSaV2B7CDYtvPTMzt54Bm85QvnYiyWVaaX+wrIzN7aYD1MsMLEw3g1QqapjEqNQ6L1hF9dDyxqXUzFvRiZa8Mt7SyBKZlD7aSNHY2DRrDrnlWa9UTbteNm70e73f3cY9y8ystf5J7pAxVmuOE2MjvC6WOS0YxxCfA5+DYSklV4BldyYVuaqKCaiQdGlZcujqpcb5G5IT9P3ukqYjtz5DkJCMYCqB/HsRkhuJbsmQfMLTz6iYktFpXfTnTFFkKMmICk0+nITkkqVKapkb8j89BxZukWitQ3KsGOU4QtG2i+3J8u1y6O81YcTUdNfhivbrMuESq+K3AbX/bM6wR1xfBGHgZ7UdQNGtlgLvKpfDcS3Q4yDxWbV7OC8My3O7Nw6aQZJmAk0z4GyuIgEmFmUR15pHe1E/6sV/gi7GQR2LcYBFmlbmFSheEUH2ouE2iJpUevYKDKd3NIh6UX8bwgWmq0uaQrxYPqDtK/BaRkjMojamP8RV08mv4jamW7i4TV+NZ5Wd88+S0CbJ01k1/1WaT8ZrbMlfgST50V+Y2GfE6ofEWxCs/jYD/655C4ozeAbjr9S34HiLTSB85mxC2OFuH4e3OpJqGuNXpPByYwVEGI7uRMl7bHUH4i5I7FrsVqNx5udsutWrqSxKvI7VdWnn7mbPutfSP26v9VhAmxmkdz/Yv9X49rRMP+FzwF71LS/8o8WL34+u8JJoCQuZVbz28gXhDbj7ADl6tZNKZEi7pefYXrjRg0P0s36/wBtON05Zoi4aTt9FFZ8mL7r+RHcQDdZRXH0HAUrWEA==)

**Comment by sxzz** [comment]
Looks like the demo works well.

**Comment by xstxhjh** [comment]
<img width="782" alt="image" src="https://github.com/vuejs/repl/assets/33480698/289815e4-f260-4f2b-b35f-96dc6eaa1591">

These are all introduced by me one by one based on the exception error prompt.
Is there a way to automatically import these required dependencies?

**Comment by pavi2410** [comment]
@xstxhjh Use https://generator.jspm.io/ to generate import maps
