### ISSUE TITLE
Suggestion: Adding HMR like in Vite

### ISSUE THREAD

**Issue by MauriceConrad** [vuejs/repl#22]
In the current implementation, the re-rendering of the components is not replacing the changed parts like HMR does in real-time but in fact re-rendering all components and mounting them again. Is there way to enable HMR like the vite's dev server offers?

**Comment by yyx990803** [comment]
That's not planned. The REPL is not meant for complex scenarios so state preservation is a lesser concern while proper HMR requires a lot of extra work.
