### ISSUE TITLE
VueUse has no effect in Repl. 

### ISSUE THREAD

**Issue by xstxhjh** [vuejs/repl#233]
I can't be sure if this is a vueuse issue or a repl issue.

Everything looks normal, but the data hasn't changed.
![image](https://github.com/vuejs/repl/assets/33480698/d4d77a97-2774-4807-ba46-0a771227c581)

https://github.com/vueuse/vueuse/issues/3879

https://repl-vuejs.vercel.app/#eNp9UMtuE0EQ/JXWXBKE2UkEF6y1FUCWCBIEAce5WLtte8K8NNPjOFrtv9Oza2/MK5d5VFV3V1cn3oVQ7TOKuahTE3UgSEg5LJXTNvhI0EHEDfSwid7CBUsvzqic8LPn49atDFp0NAlvWMmEbHwsFco13iUCWsctEixK00uXjXnxxHVwmMHjDHS6y5R0i9xs8feIy7EHF9ZytMxm+UNog1kT8g+gbvW+zFgoMcqVGHBmdtfLj2iMhwcfTVtL/h8Zrll27AL6Hvh+5LuWBRw6Hl+1nAaJmRiTeGXXobpP3nGMXRGrI5GUmMOAFOw8k0IosSMKaS5l0zqub9HofawcknTBynP5zfVV9ba6ki8xWSVKw165ng1Q4vA2evvH+MbboA3Gu0Caw/3NxpqXf/g0YBQzzk54s8Pm5z/w+3QY3X6NmDDu2fvEncIt9Or7FzzweyKtb7M5bvof8hsmb3LxOMreZ9ey7TPd4PZ2SFO77Y+0OhC6dFqqGB3SGPRKcGQfnln9ye7r6s2UYv8LMDIDqg==

**Comment by Sight-wcg** [comment]
```
{
  "imports": {
    "vue": "https://cdn.jsdelivr.net/npm/@vue/runtime-dom@3.4.21/dist/runtime-dom.esm-browser.js",
    "vue/server-renderer": "https://cdn.jsdelivr.net/npm/@vue/server-renderer@3.4.21/dist/server-renderer.esm-browser.js",
    "vue-demi": "https://cdn.jsdelivr.net/npm/vue-demi@0.14.7/lib/index.mjs",
    "@vueuse/shared": "https://cdn.jsdelivr.net/npm/@vueuse/shared@10.9.0/index.mjs",
    "@vueuse/core": "https://cdn.jsdelivr.net/npm/@vueuse/core@10.9.0/index.mjs"
  },
  "scopes": {}
}
```
