### ISSUE TITLE
how add Tailwind

### ISSUE THREAD

**Issue by kr1ke** [vuejs/repl#240]
how i can add Tailwind in playground?

the only way I found is to insert this code into the vue component:

```
const tailwindScript = document.createElement('script')
tailwindScript.setAttribute('src', 'https://cdn.tailwindcss.com')
document.head.appendChild(tailwindScript)
```

but is there a way to run this code by default before starting the sandbox?

**Comment by sxzz** [comment]
You can pass a prop `previewOptions` to the Repl component.

```vue
<Repl :preview-options="{ headHTML: '<script ... />' }" />
```
