### ISSUE TITLE
Indentation Logic Inconsistency and Code Folding Errors

### ISSUE THREAD

**Issue by ericgll0104** [vuejs/repl#259]
Problem Description:
- Text:
	① The logic of left indentation and right indentation is inconsistent.
	② Due to ①, when the right side (`__sfc__={...}`) is folded, there is an unindentable value (in this case, `msgRef3`), which leads to an error in folding (Monaco folds based on indentation).
- Video: [https://github.com/vuejs/repl/assets/134293035/33573c48-766d-468e-9bd7-3f2d2b7dd101](https://github.com/vuejs/repl/assets/134293035/33573c48-766d-468e-9bd7-3f2d2b7dd101)

Example shown in the video: https://play.vuejs.org/#eNp9kstugzAQRX/F8oZWSoMSWKUkUltl0S7aKu3SG0oGQgq25UcaCfHvHZtAHoqyY+45tu4gN/RJyvHOAp3RRGeqlIZoMFYuGC9rKZQhDVGQk5bkStQkQDVgnPFMcG1ISuZk8thPPzhNh6nWxQryCWZ4/i44jMF9zzMk0YU9PbenR3uNJL6wo3M7OtpdEJ/z2PEk7LbE/XAwUMsqNYATIclmsmiaoXfbJiEmnpRcWkN2D7VYQzVn9OAwSkIUkvDkHjqiRmOLvCzGWy04/tjG3cFoJmpZVqA+pCmxJaMz4oljaVWJvzefGWVh1OfZBrLfK/lW713G6KcCDWoHjA7MpKoA0+Hl1zvs8XuAuIGt0L4BV6BFZV3HTnu2fI21Tzzf9tU/j5IX33q5N8B1v5Qr6szW+4zik3m5sfqxbjSO/TnGW9r+A2JC2rc=

**Comment by sxzz** [comment]
This is not within the scope of the `repl` repository. Also, the code output by Vue SFC compiler does not currently guarantee code style; you can submit an issue to vue-core.
