### ISSUE TITLE
[bug]: 生产环境jsx编译报错

### ISSUE THREAD

**Issue by rashagu** [vuejs/repl#261]
https://repl-vuejs.vercel.app/#eNp9ksFOwzAMhl8l5NJNmlrBOE3dJECTgAMgQOKSS9W6pSNNosQZlaq+O07Gyg7Azfb3J/5jZ+BXxqR7D3zFc1fa1iBzgN5shGo7oy2ygVmo2chqqzuWkDSZ0I3uzHc9zUKSousJC1Vq5ZB1rmHrcHyW3IKUmr1pK6uzZC5Unh26UR9KEDojCwTKGMvjtRnFeXYC+IKjo3vrtkl3TityPAS54CXpWwn20WBLfQVfsUgCK6jt532sofWwONbLdyg/fqnvXB9qgj9ZcGD3IPjEsLAN4AFvXx6gp3iCna68JPU/8Bmclj54PMiuvarI9okuur2Lw21V8+q2PYJyx0cFo0E5Rr3gtIswqr+e/mN3mV7Gc0KNNMXjomiA0Mc9VlAXXiKbzdebQdigtfQJrGJ51e435xfLPAtBQCMfvwA9HLs9

**Comment by sxzz** [comment]
截图并没有上传成功，并且你需要提供更多的信息。


> [「请提供最小重现」](https://antfu.me/posts/why-reproductions-are-required-zh)

**Comment by rashagu** [comment]
https://repl-vuejs.vercel.app/#eNp9ksFOwzAMhl8l5NJNmlrBOE3dJECTgAMgQOKSS9W6pSNNosQZlaq+O07Gyg7Azfb3J/5jZ+BXxqR7D3zFc1fa1iBzgN5shGo7oy2ygVmo2chqqzuWkDSZ0I3uzHc9zUKSousJC1Vq5ZB1rmHrcHyW3IKUmr1pK6uzZC5Unh26UR9KEDojCwTKGMvjtRnFeXYC+IKjo3vrtkl3TityPAS54CXpWwn20WBLfQVfsUgCK6jt532sofWwONbLdyg/fqnvXB9qgj9ZcGD3IPjEsLAN4AFvXx6gp3iCna68JPU/8Bmclj54PMiuvarI9okuur2Lw21V8+q2PYJyx0cFo0E5Rr3gtIswqr+e/mN3mV7Gc0KNNMXjomiA0Mc9VlAXXiKbzdebQdigtfQJrGJ51e435xfLPAtBQCMfvwA9HLs9

**Comment by sxzz** [comment]
Fixed via e55baa4
