### ISSUE TITLE
用ip 访问报错

### ISSUE THREAD

**Issue by Greasen** [vuejs/repl#27]
用ip 访问报错，提示 Cannot set properties of undefined (setting 'name') ； 
控制台提示 Cannot read properties of undefined (reading 'digest') ；
Cannot set properties of undefined (setting 'name') ； 

但是本地用 localhost 访问正常

**Comment by Greasen** [comment]
和 #25 问题描述一致。

**Comment by linpeng118** [comment]
是浏览器中crypto 这个用法导致的，我重写了里面的hashId方法，使用其他加密方式来代替crypto ，就可以解决了。

**Comment by Greasen** [comment]
> 是浏览器中crypto 这个用法导致的，我重写了里面的hashId方法，使用其他加密方式来代替crypto ，就可以解决了。

对，我知道是这个方法导致的问题，我部署到 https 上了，解决问题了；但是还是希望官方能解决这个问题，不能局限部署条件或者重写 hashId 方法；

**Comment by linpeng118** [comment]
> > 是浏览器中crypto 这个用法导致的，我重写了里面的hashId方法，使用其他加密方式来代替crypto ，就可以解决了。
> 
> 对，我知道是这个方法导致的问题，我部署到 https 上了，解决问题了；但是还是希望官方能解决这个问题，不能局限部署条件或者重写 hashId 方法；

哈喽，尤大已经修改了，我今天才注意看，没有用crypto了，改为从hash-sum依赖生成hash值

**Comment by ellieot** [comment]
> > > 是浏览器中crypto 这个用法导致的，我重写了里面的hashId方法，使用其他加密方式来代替crypto ，就可以解决了。
> > 
> > 
> > 对，我知道是这个方法导致的问题，我部署到 https 上了，解决问题了；但是还是希望官方能解决这个问题，不能局限部署条件或者重写 hashId 方法；
> 
> 哈喽，尤大已经修改了，我今天才注意看，没有用crypto了，改为从hash-sum依赖生成hash值

大佬你好，可以帮忙看看我提的issue吗，我还在学习中，难以阅读源码找到解决方案，如果你知道，感谢告诉我一下，麻烦了 #52
