### ISSUE TITLE
Add a switch button

### ISSUE THREAD

**Issue by btea** [vuejs/repl#282]
Currently, `autoSave` is reactive, can we add a toggle button like `Show Error`?

![image](https://github.com/user-attachments/assets/50e9910a-68f6-4cab-86e8-d9ae3c5480b6)

**Comment by sxzz** [comment]
Good idea

**Comment by btea** [comment]
I tried it briefly, and found that `autoSave` and `Show Error` are not the same. `autoSave` is passed in through props, and it seems that it cannot be modified directly. What do you think is a better way to deal with it? 🤔

**Comment by sxzz** [comment]
We can let `autoSave` be a model - use `defineModel` instead.
