### ISSUE TITLE
v1.0.0 will trigger doneAddFile multiple times

### ISSUE THREAD

**Issue by zhixiaoqiang** [vuejs/repl#29]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/25545093/162112188-f364ed64-6edf-44a7-b7d9-066289458403.gif">

[github](https://github.com/zhixiaoqiang/sfc-playground-vant)、[preview](https://sfc-playground-vant.vercel.app/)

https://github.com/vuejs/repl/blob/35b6f1a38611e31b9adbe7540d789be144e33bdc/src/editor/FileSelector.vue#L80-L89

**Comment by yyx990803** [comment]
918de7f
