### ISSUE TITLE
Bug: Missing TypeScript type hints on mouse hover.

### ISSUE THREAD

**Issue by Orange-001** [vuejs/repl#292]
While using this library, I've noticed that the Monaco Editor is unresponsive on mouse hover, lacking TypeScript type hints. This affects the development experience. Here is a reproduction example: [repl-test](https://github.com/Orange-001/repl-test).

As shown in the image, when hovering over ref, the Monaco Editor is unresponsive and lacks TypeScript type hints.
![image](https://github.com/user-attachments/assets/180bad6e-0679-4184-b986-5b6409c0bf82)

**Comment by sxzz** [comment]
```
optimizeDeps: {
  exclude: ['@vue/repl'],
}
```
See https://github.com/vuejs/core/blob/35785f3cd7bd86cbec3f8324022491da2d088b61/packages-private/sfc-playground/vite.config.ts#L27-L29

**Comment by sxzz** [comment]
Added an example to README

**Comment by Orange-001** [comment]
> ```ts
> optimizeDeps: {
>   exclude: ['@vue/repl'],
> }
> ```
> 
> See https://github.com/vuejs/core/blob/35785f3cd7bd86cbec3f8324022491da2d088b61/packages-private/sfc-playground/vite.config.ts#L27-L29查看 https://github.com/vuejs/core/blob/35785f3cd7bd86cbec3f8324022491da2d088b61/packages-private/sfc-playground/vite.config.ts#L27-L29

Thanks for your help!
