### ISSUE TITLE
Not support the display of webgl content?

### ISSUE THREAD

**Issue by songxp03** [vuejs/repl#50]
是不是不支持webGL内容的展示啊？
使用了，echarts-gl，没有成功哦。echarts一点问题没有。

**Comment by sxzz** [comment]
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required
