### ISSUE TITLE
移动端报错

### ISSUE THREAD

**Issue by Tyh2001** [vuejs/repl#51]
## 描述

在 `pc` 端可以正常使用，但是在移动端报错：

```shell
undefined is not an object (evaluating '__import_1__.install')
```

## 项目地址

仓库：https://github.com/FightingDesign/playground

线上地址：https://tianyuhao.cn/playground

## 错误截图

移动端截图：

![3f53df219a4a9321915004f2a71ce7a](https://user-images.githubusercontent.com/73180970/189532365-99e1231a-e233-4c26-9177-0ed7de48e052.jpg)

**Comment by Sight-wcg** [comment]
该项目使用了 [Import Maps](https://caniuse.com/import-maps) ,  需要 chromium 89 及以上内核版本的浏览器。 测试在 `Edge for Android`(chromium104.0.1293.70), `QQ Browser for Android`(x5 内核, 基于chromium 89.0.4389.72) 上正常运行。

国内移动端浏览器使用的内核普遍比较旧，也就腾讯定制的 x5 新一些。推荐用 Chrome, Edge 移动版，或基于 x5 内核的浏览器（QQ 浏览器，QQ，微信内置浏览器 ）访问，可确保正常使用。

**Comment by Tyh2001** [comment]
这个截图是什么工具测试的？

按照道理来说不应该是版本的问题，因为我使用的是 iphone11 的 Safari 浏览器，还有最新的手机版 Chrome，都会有同样的问题，这两个浏览器都不会是比较旧的内核吧？

有什么可以从代码层面优化的方式吗？

@Sight-wcg

**Comment by Sight-wcg** [comment]
> 这个截图是什么工具测试的？

测试工具是 [Can i use](https://caniuse.com/import-maps)
![image](https://user-images.githubusercontent.com/26325820/189575852-33bc87f8-d42c-4238-bd48-6355917f9d5c.png)

> 按照道理来说不应该是版本的问题，因为我使用的是 iphone11 的 Safari 浏览器，还有最新的手机版 Chrome，都会有同样的问题，这两个浏览器都不会是比较旧的内核吧？

 Ios 由于 Apple Store 审核政策，第三方浏览器只能使用 Safari 的内核，目前 Safari on ios 不支持 Import Maps

> 有什么可以从代码层面优化的方式吗？

由于我没有 ios 设备，无法测试，只能提供一些参考，需要你自己去测试是否能解决问题。
- 方式一：克隆 @vue/repl 到本地机器上然后自行将其链接(pnpm link), 修改 @vue/repl 以下部分
https://github.com/vuejs/repl/blob/356f65d9f6c5978412b1f439a62e59d621710bf4/src/output/srcdoc.html#L253 以升级 [es-module-shims](https://github.com/guybedford/es-module-shims) 版本，1.5.6 提供了 ios webview 的支持。
- 方式二：在你的项目中使用 pnpm patch 制作 @vue/repl 补丁进行测试，修改同上

https://github.com/guybedford/es-module-shims/pull/298
https://github.com/guybedford/es-module-shims/pull/292

**Comment by Tyh2001** [comment]
好的 我试下 感谢！

> > 这个截图是什么工具测试的？
> 
> 测试工具是 [Can i use](https://caniuse.com/import-maps) ![image](https://user-images.githubusercontent.com/26325820/189575852-33bc87f8-d42c-4238-bd48-6355917f9d5c.png)
> 
> > 按照道理来说不应该是版本的问题，因为我使用的是 iphone11 的 Safari 浏览器，还有最新的手机版 Chrome，都会有同样的问题，这两个浏览器都不会是比较旧的内核吧？
> 
> Ios 由于 Apple Store 审核政策，第三方浏览器只能使用 Safari 的内核，目前 Safari on ios 不支持 Import Maps
> 
> > 有什么可以从代码层面优化的方式吗？
> 
> 由于我没有 ios 设备，无法测试，只能提供一些参考，需要你自己去测试是否能解决问题。
> 
> * 方式一：克隆 @vue/repl 到本地机器上然后自行将其链接(pnpm link), 修改 @vue/repl 以下部分
>   https://github.com/vuejs/repl/blob/356f65d9f6c5978412b1f439a62e59d621710bf4/src/output/srcdoc.html#L253
>    以升级 [es-module-shims](https://github.com/guybedford/es-module-shims) 版本，1.5.6~1.5.8 修复了一些 ios webview 上的问题。
> * 方式二：在你的项目中使用 pnpm patch 制作 @vue/repl 补丁进行测试，修改同上
> 
> 参考 [guybedford/es-module-shims#304](https://github.com/guybedford/es-module-shims/pull/304) [guybedford/es-module-shims#298](https://github.com/guybedford/es-module-shims/pull/298) [guybedford/es-module-shims#292](https://github.com/guybedford/es-module-shims/pull/292)
