### ISSUE TITLE
How to customize styles and layout correctly?

### ISSUE THREAD

**Issue by ellieot** [vuejs/repl#52]
For example, I want a dark theme. I added class="dark" to the parent container, which meets the expectations. Now I want the code and output to be arranged vertically. There is a description of "vertical" in the css file, but it does not work after adding it. I try to read the source code to solve the problem myself, but some variables do not have proper explanations, which is difficult to read. So please ask me how to make some customized settings. Especially vertical arrangement.

**Comment by Sight-wcg** [comment]
https://github.com/vuejs/repl/blob/356f65d9f6c5978412b1f439a62e59d621710bf4/src/Repl.vue#L15
`<Repl layout="vertical"  />`

You can use 'flex-direction: row-reverse' or 'flex-direction: column-reverse' to reverse the position of the editor and output.

**Comment by ellieot** [comment]
> https://github.com/vuejs/repl/blob/356f65d9f6c5978412b1f439a62e59d621710bf4/src/Repl.vue#L15
> 
> 
> `<Repl layout="vertical" />`
> You can use 'flex-direction: row-reverse' or 'flex-direction: column-reverse' to reverse the position of the editor and output.

thanks a lot, and is there any way to compile my customized single html file, instead of rending the sfc file as default? I had tried to read the source code but still cant solve this...

**Comment by Sight-wcg** [comment]
> > https://github.com/vuejs/repl/blob/356f65d9f6c5978412b1f439a62e59d621710bf4/src/Repl.vue#L15
> > 
> > `<Repl layout="vertical" />`
> > You can use 'flex-direction: row-reverse' or 'flex-direction: column-reverse' to reverse the position of the editor and output.
> 
> thanks a lot, and is there any way to compile my customized single html file, instead of rending the sfc file as default? I had tried to read the source code but still cant solve this...

https://github.com/vuejs/repl/blob/4af73cb41c716f0bcb4f8b14d643d2417534197a/src/store.ts#L182
The main file is specified as 'xxx.html'.
example: https://stackblitz.com/edit/vitejs-vite-u9fbdm
