### ISSUE TITLE
Suggestion: Toggle popups for error reporting in tutorials

### ISSUE THREAD

**Issue by gnuion** [vuejs/repl#64]
![image](https://user-images.githubusercontent.com/16549839/210180079-efd0868e-8ef5-438d-aa83-044755019bc4.png)

While solving the [tutorial challenges]( https://vuejs.org/tutorial/#step-8), it would be nice if there wouldn't be popups hiding my code while I am writing it.

**Comment by sxzz** [comment]
Done via #98
