### ISSUE TITLE
Add import for Pinia

### ISSUE THREAD

**Issue by vanillajonathan** [vuejs/repl#66]
Add import for [Pinia](https://pinia.vuejs.org/).

**Comment by sxzz** [comment]
You can configure Import Map yourself.

**Comment by vanillajonathan** [comment]
Possibly, but it seems inconvenient and tricky. Someone probably wouldn't know where to find a `pinia.esm-browser.js` file. It would be much more user-friendly if it already had an entry in the import map for Pinia.

**Comment by sxzz** [comment]
There are tons of deps in npm. We cannot add all of them (like Vue Router, Pinia, Vuex, UI library...)

`vuejs/repl` is designed more for skilled developers.

**Comment by vanillajonathan** [comment]
Why couldn't Pinia (and some others) be added, aren't they lazy loaded? So it shouldn't affect bundle size or performance?

I think skilled developers probably have their local development environments setup on their machines. I think the `vuejs/repl` via the Vue SFC Playground is often used by novice developers.
