### ISSUE TITLE
Update sucrase version to support TypeScript 4.9

### ISSUE THREAD

**Issue by xiaosen7** [vuejs/repl#70]
Hello, thank you so much for developing such a nice library, but I found some typescript(4.9) syntax support not very good when using it. The version of surcrase shows 3.21.0 in the pnpm-lock.yaml file, but the latest version of sucrase is 3.29.0 and the syntax for Typescript4.9 is already supported, should the sucrase version be updated?

**Comment by xiaosen7** [comment]
Here is a pr for this issue. https://github.com/vuejs/repl/pull/71

**Comment by yyx990803** [comment]
closed via c117a6390c3c16fcd91abd03d432b16163ec4285
