### ISSUE TITLE
Vue2可以用吗?

### ISSUE THREAD

**Issue by kakage553656552** [vuejs/repl#75]

**Comment by sxzz** [comment]
No.
不能。

**Comment by Sight-wcg** [comment]
https://github.com/Thy3634/vue2-repl

**Comment by kakage553656552** [comment]
> https://github.com/Thy3634/vue2-repl

这个可以吗?我咋看里面还是setup语法呢?

**Comment by Sight-wcg** [comment]
> > https://github.com/Thy3634/vue2-repl
> 
> 这个可以吗?我咋看里面还是setup语法呢?

我可能误解可能你的意思了, 这个也不能

**Comment by xxholly32** [comment]
主要还是因为 https://github.com/vuejs/vue/issues/12686 这个，不过可以实现一个服务端解析，客户端去渲染的方式

**Comment by xxholly32** [comment]
https://github.com/xxholly32/vue2-sfc-playground  服务端实现渲染 vue2+ setup，demos:

[vue2 + components](https://vue2-sfc-playground.vercel.app/#eNq1UDFuwzAM/AqrxS3QWGhHwwladOkPunAJbCVxa0mEJHsR9PdSUpKpHTJk490Rd+RF8U7UrosSnej94CYK4FVYaIdm0mRdgAhOHSDBwVkNDa82V+nDaqo8ilZmlK1QoEEzWOMDaH+EbTZ4bD7VPFv4sm4eH5onNL2seZzEIChN8z4oRgD9OK1l4PH0soux+KTUS0ZnfjK0BFg32o5q3qLgDRQXsRwmq5esZr28RohnUR/Y6D21394a/j7mZTwLHkUHhclc+anj4RQC+U7KxdDPsR2sliy9vXKCD3lsldfslwsASGgSJ11aua3gf/vLdvet76/C0i8X2rgU)

[vue2 + echarts](https://vue2-sfc-playground.vercel.app/#eNp1Uktv1DAQ/isjIzVZFJJ9dAGF3arlJXGoOIDEoe4hStyNIbEt2wmNVvnvjO0kUIlePK9v5hvPzJncKJX2HSM5OZhSc2XBMNupKyp4q6S2cJbiVnbCsmqEBy1boATxlCyAl1AYYGVdaGsCIpqs6B0VVCz5cbyC4xWcqQDoCw0e9BHxR6hk2bVM2PTE7KeGOfX98KWKo7bgIlphnZDSDh9cEmZMFCkX3MZzpb9AqSyXwvPDZGCSpwZ4vHnkJp8tADsolkNUFpadpB6iZA5UhS1yuItupYgSiL53zIkfrPJW3TnxWXMnvhXWi05E9yF9nMoM/2friwbLPYUapjlD7N2MXZKWXjb7dQLbnXu2l/hs3iaw2e3xuXyD5uv1/dL9QtVwMTMhV1B8k+PTAV1czANO8Qi+emccYm6y44qKQxauBO8DDcta1eDU0AI4VLwHXh0pcUujJDgz9KJ2yP7Bomns0Dj1hcOGbyppuKPKQTME8p75bdaMn2qbw2a97mvvkT3TD438nUPNq4q5LeOnsDNfkyQkHOartlDpTyMF3rYnoFPAULKsYzrmHJXaWmXyLOuE+nVKS9lmGLre4geMdWrKTIv1KJkGTMl0g8+lT+HrfbpLd6HMfLVzKb8EbJ+MfwCmZSFj)

[vue2 + tailwindcss1](https://vue2-sfc-playground.vercel.app/#eNrtWEtz4zYM/isY97I7Y1rvB73edHtvD32d6h4YCpLYSBSXpOJkdvLfC0mO89j23Kzrg20QFMAPwAfK5JfVD8ZsbkdcbVc7J60yHhz60VztNcBe74JFSUMaeOxNJzzOk7tK3c4CiQZkJ5z7uF95vPOssXjPKmFv0MKsuHPQX7Nyv7r6BZ0ZtFO3CFLYysG7CAKI6ZOAHDr3/sOsh3oYPFoaOAd1h3dg7GDQeoU0Hizg51F00KJqWu828Lt2hMy1YNrBD26zC6YIJognZLOX6YsdrDDAepYQHopxinP5vHj+wOqx68D12wOLghj6ahaSBc7siACDmd0c8/Dc/rphh1Z5BDuMusKKdQ24VlTDYZKGW7R1R3Krqgr14i966fvk92vPcrKHlqWUU3D+vsNJL+RNM6/GVC8a3MJou3et98Ztg2BWuc14zNRGDn0wZ4tFWZzwosx4lBYlk0WW8JTXdZmG3x8+8jB8/4GQ7IKner/CY1j6L/hP0Ig+T8GQeUvVPloTMdKFJfHdFPJP91RWUSnd7II2eW70fM0nq6/I5vojmhdLTiy9+nGw2IMybuyhGjrikVMeRI9+TezTDqUn8lug5Y1yShIIwE75DSyEOrl6kQwaC2gt1oTrOwr6VKfBVmiZh6MwI+0mxoKhaE+tcQoD2qms23lssYLREOWlcAh6YBOJbKc0grdUaILGDqrC10n+7aA8dc4uEE/FeoZ2kY90P+n/z+RPeZHwMi7yOIkYT+s6qyQP46j4j8jfj7KFbtDNFOPba4SfR+HUmhboDfkAJ4xCTYXGW9QKPXwe1fXoKtGDuAYUa1IItIIo3wmJ9KvHnlQ07YjcWtAqaxBSjk70I70mRKNpUtP+jsdd/NJ0Z/jGCZMyT3hSFDxjecyzVCQyrMPs3N44v7aDJWbMz134fL58jqKwTHkYlXHKIpkVdSaiXPLywucLn7/JE0HGk4ynaVZELEXOY9qq81Tyy4ngXP4IXTrtbRw/yjwL86xI07xgMk15ntSyKIv8/DptPtJQU3nqk1eU/mZ78bKJvKVNZLmyfNQ8SrvgdHG5Wq/UlGrPemE2f7lB08Xnl9n8OOH2qy3MmklHN6PTeL967ORRm5tm7l+a+hTTCs5P4gZdT/6mAAAe1otHurycrP/4J3MvVHdQuqJnPkWLm0fVZrb7c68fVg9/Aye2CWk=)

[vue2 + less](https://vue2-sfc-playground.vercel.app/#eNpNkD1uwzAMha/CanELNBbS0XWMdOvQI2gxHMV2qz+IdIBC0N1DyRmy8ek9fqSYxFcI7W3TohM9TnENBKhpC4Nyqw0+EiSI+goZrtFbaDjaKKfc5B0SWJzhVPzX5lsb4+FHI740b8r1cqcxhwVpG8xImhVAf1lvteByOQ4pVUzOvWRVA3JP9PKpjyXSv9FgRjeflDA8SQk2zrSS0YfJGx873uXyWcLLEVJhPZ6fQ+znumDBDeJd7B892DG0v+gdn6K2qofBY7odVt74AEUrsRAF7KTcXPib28lbydb5g3dHKmWr0TJPidLJA7PIdySufSE=)

**Comment by yyx990803** [comment]
This project only supports Vue 3.

**Comment by zh-lx** [comment]
实现了一个支持 vue2/3和 react的通用 playground，欢迎大家体验：https://play.fe-dev.cn/?appType=vue2
