### ISSUE TITLE
It would be nice if we could support importing full components into vue

### ISSUE THREAD

**Issue by xxholly32** [vuejs/repl#77]
Here's a [demo](https://sfc.vuejs.org/#eNqNkk1v2zAMhv8KoUs2oJaAYafAK7qhPexWYIddfHEc2lMnyYJINQuC/PfRVoN8FAV8Eim+7yOR0kF9j1G/ZlRrVVOXbGQg5Bzvm2B9HBPDARL2cIQ+jR5WIl1dlJ7cj8w8hlMdVujQY+AqukyiNAYsw846BxuEIWHLUHZPiEx4Qz9XnwrsWVhviit80Qrg04XwcxNqU1qRJiRh9NG1jJIB1OiqNO6gcy3Rt0b5TfW1UXOpFDdzP/eP2LfZcW3OW7ca4H1EQcRkfZv2Qnku0RIT5a5DIjH9KtESkw39KI6fsiyR79oUbBjE8btES0zbNgyYxPM4B7eWOZcBSlKbi8lKSrx3U/jw9niN+sMcaW1MDvHvoLvRi/n8fA9fzNYSGxu2+E930zDmp5sx6k4VTOXbqF9oDPJDD9MNZAxzQeRrmHemPfk5U34+k/pu+tcvpMc0GIl0yoGtR43kq420QJgE3Ki7E+PyctewJQ302TntbdD+CionGznpFVOVUIRpGu7HF72RvrvshD024aiO/wHPQk0f) of an element-plus I wrote

and this is [element-plus official demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcm93IGNsYXNzPVwibWItNFwiPlxuICAgIDxlbC1idXR0b24+RGVmYXVsdDwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj5QcmltYXJ5PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiPlN1Y2Nlc3M8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJpbmZvXCI+SW5mbzwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cIndhcm5pbmdcIj5XYXJuaW5nPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCI+RGFuZ2VyPC9lbC1idXR0b24+XG4gIDwvZWwtcm93PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

I've seen a lot of community implementations like <https://element-plus.run>, which is actually bad for developers, and the pain point is that we can't bring in a whole component library at once. As you can see, the lack of el-rows in my demo caused my code to only partially render

So I have a proposal

```
// if it works will be great 
import { use } from 'vue'
import ElementPlus from 'element-plus'
use(ElementPlus)
```

**Comment by xxholly32** [comment]
thanks bro, it works

**Comment by fanckush** [comment]
@Sight-wcg in the playground link you sent, how does the playground know to import the element-plus npm package? does that happen automatically
