### ISSUE TITLE
missing 1.3.5 commits

### ISSUE THREAD

**Issue by Himself65** [vuejs/repl#83]
![image](https://user-images.githubusercontent.com/14026360/230738951-4158c9cc-2fbd-4884-9b69-e7736763c9e1.png)

![image](https://user-images.githubusercontent.com/14026360/230738940-8d895408-509a-486b-9c04-6f3944be38db.png)

![image](https://user-images.githubusercontent.com/14026360/230738967-07b44b07-f7e6-4c9c-995a-63aaf5e8d580.png)

**Comment by yyx990803** [comment]
Forgot to push after release...
