### ISSUE TITLE
About the introduction of third party packages

### ISSUE THREAD

**Issue by Alfred-Skyblue** [vuejs/repl#87]
I would like to create a feature that allows importing third-party packages, but I have found that there is no way to query all available third-party packages. Can I write a common list here for loading these third-party packages? I am willing to contribute to this. I'm wondering if the official team has any plans regarding this.

**Comment by Lsscr** [comment]
The idea sounds good.  hope it will be realized soon 👀

**Comment by sxzz** [comment]
I think it’s not necessary. Cuz we can import any ESM packages from npm CDN, like unpkg or jsdelivr.

**Comment by Alfred-Skyblue** [comment]
> I think it’s not necessary. Cuz we can import any ESM packages from npm CDN, like unpkg or jsdelivr.

My idea is that we can use CDN to import any esm packages, but for convenience, we can also list some commonly used packages for quick installation, which does not conflict with the current design in principle.

**Comment by sxzz** [comment]
Maybe you can create a new project for such a collection.
