### ISSUE TITLE
Suggestion: UI Optimization

### ISSUE THREAD

**Issue by liting-yes** [vuejs/repl#93]
It is recommended to hide the ssr tab button in non-ssr mode

<img width="727" alt="Screenshot 2023-06-13 at 01 01 44 1" src="https://github.com/vuejs/repl/assets/69500429/6c1d0af1-ef67-4d43-be36-54cdd0342ba0">

**Comment by yyx990803** [comment]
I don't think it makes much difference. The tab is mainly for debugging, not for UX.

**Comment by liting-yes** [comment]
get it 🤓
